version: 2.1
jobs:
  lint:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: node:12.22.7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Polymer3 Build
          command: npm run build
          no_output_timeout: 25m

  build_and_deploy:
    working_directory: ~/code
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: node:12.22.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Exporting revision number
          command: |
            REVNO=${CIRCLE_SHA1}
            BUILDDATE=$(date -u +%F_%T)
            sed -i "0,/revNo/s//$REVNO/" package.json
            sed -i "0,/bDate/s//$BUILDDATE/" package.json
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
          # build and push Docker image
      - run:
          name: Building the image
          no_output_timeout: 25m
          command: |
            TAG=${CIRCLE_BRANCH}
            docker build -t unicef/etools-menu:$TAG .
      - run:
          name: Pushing to Docker Hub
          command: |
            TAG=${CIRCLE_BRANCH}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push unicef/etools-menu:$TAG

workflows:
  version: 2.1
  build_and_lint:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - main
                - staging
                - develop
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
                - staging
                - develop
